#!/usr/bin/env node
'use strict';

/**
 * Builds content/blog/*.md into apps/api/public/blog/*.html plus the /blog
 * index, and refreshes the blog block in the sitemap.
 *
 * The generated HTML is committed. The Fly build context is apps/api, so the
 * markdown sources never reach the image and nothing renders at request time.
 *
 *   node tools/blog/build.js            build published posts
 *   node tools/blog/build.js --check    lint only, write nothing (drafts included)
 *   node tools/blog/build.js --drafts   also build drafts (noindex, not in sitemap)
 *
 * See docs/VERGO-BLOG-SYSTEM.md for the editorial rules this enforces.
 */

const fs = require('fs');
const path = require('path');

const { PostError, loadPost, splitFrontmatter } = require('./post');
const { MarkdownError } = require('./markdown');
const { lintPost } = require('./lint');
const { renderIndex, renderPost, ORIGIN } = require('./template');

const repoRoot = path.resolve(__dirname, '..', '..');

const SITEMAP_START = '  <!-- BLOG:START - generated by tools/blog/build.js, do not edit by hand -->';
const SITEMAP_END = '  <!-- BLOG:END -->';

function parseArgs(argv) {
  const options = {
    check: false,
    drafts: false,
    contentDir: path.join(repoRoot, 'content', 'blog'),
    outDir: path.join(repoRoot, 'apps', 'api', 'public'),
  };

  for (let i = 0; i < argv.length; i += 1) {
    const arg = argv[i];
    if (arg === '--check') options.check = true;
    else if (arg === '--drafts') options.drafts = true;
    else if (arg === '--content') options.contentDir = path.resolve(argv[++i]);
    else if (arg === '--out') options.outDir = path.resolve(argv[++i]);
    else {
      console.error(`Unknown argument: ${arg}`);
      process.exit(2);
    }
  }

  return options;
}

function readPosts(contentDir) {
  if (!fs.existsSync(contentDir)) {
    console.error(`ERROR: content directory not found: ${contentDir}`);
    process.exit(2);
  }

  return fs
    .readdirSync(contentDir)
    .filter((name) => name.endsWith('.md') && !name.startsWith('_') && name !== 'README.md')
    .sort()
    .map((name) => {
      const file = path.join(contentDir, name);
      const raw = fs.readFileSync(file, 'utf8');
      return { name, file, raw };
    });
}

function writeIfChanged(file, contents) {
  fs.mkdirSync(path.dirname(file), { recursive: true });
  if (fs.existsSync(file) && fs.readFileSync(file, 'utf8') === contents) return false;
  fs.writeFileSync(file, contents);
  return true;
}

function updateSitemap(outDir, posts) {
  const sitemapPath = path.join(outDir, 'sitemap.xml');
  if (!fs.existsSync(sitemapPath)) {
    console.warn(`WARN: sitemap not found, skipping: ${sitemapPath}`);
    return false;
  }

  // With no published posts the index carries a noindex meta, so it must not
  // appear in the sitemap either.
  const entries = posts.length === 0 ? [] : [
    { loc: `${ORIGIN}/blog`, lastmod: posts[0].updated, priority: '0.7', changefreq: 'weekly' },
    ...posts.map((post) => ({
      loc: `${ORIGIN}${post.route}`,
      lastmod: post.updated,
      priority: '0.6',
      changefreq: 'monthly',
    })),
  ];

  const block = [
    SITEMAP_START,
    ...entries.map((entry) => [
      '',
      '  <url>',
      `    <loc>${entry.loc}</loc>`,
      `    <lastmod>${entry.lastmod}</lastmod>`,
      `    <changefreq>${entry.changefreq}</changefreq>`,
      `    <priority>${entry.priority}</priority>`,
      '  </url>',
    ].join('\n')),
    '',
    SITEMAP_END,
  ].join('\n');

  const xml = fs.readFileSync(sitemapPath, 'utf8');
  let next;

  if (xml.includes(SITEMAP_START) && xml.includes(SITEMAP_END)) {
    const before = xml.slice(0, xml.indexOf(SITEMAP_START));
    const after = xml.slice(xml.indexOf(SITEMAP_END) + SITEMAP_END.length);
    next = before + block + after;
  } else {
    const closing = '</urlset>';
    if (!xml.includes(closing)) {
      console.warn('WARN: sitemap has no </urlset>, skipping');
      return false;
    }
    next = xml.replace(closing, `${block}\n\n${closing}`);
  }

  return writeIfChanged(sitemapPath, next);
}

function main() {
  const options = parseArgs(process.argv.slice(2));
  const sources = readPosts(options.contentDir);

  const posts = [];
  const failures = [];
  let warningCount = 0;

  for (const source of sources) {
    let post;
    try {
      post = loadPost(source.name, source.raw);
    } catch (error) {
      if (error instanceof PostError || error instanceof MarkdownError) {
        failures.push({ name: source.name, errors: [error.message] });
        continue;
      }
      throw error;
    }

    const { body } = splitFrontmatter(source.raw, source.name);
    const { errors, warnings } = lintPost(post, body);

    if (warnings.length) {
      warningCount += warnings.length;
      console.log(`${source.name}:`);
      warnings.forEach((warning) => console.log(`  warn  ${warning}`));
    }

    if (errors.length) {
      failures.push({ name: source.name, errors });
      continue;
    }

    posts.push(post);
  }

  const duplicateSlugs = posts
    .map((post) => post.slug)
    .filter((slug, index, all) => all.indexOf(slug) !== index);
  if (duplicateSlugs.length) {
    failures.push({ name: 'content/blog', errors: [`duplicate slugs: ${[...new Set(duplicateSlugs)].join(', ')}`] });
  }

  if (failures.length) {
    console.error('');
    console.error(`Posts with errors: ${failures.length}`);
    for (const failure of failures) {
      console.error(`- ${failure.name}`);
      failure.errors.forEach((error) => console.error(`  ${error}`));
    }
    console.error('');
    console.error('Nothing was written. Fix the errors above and run again.');
    process.exit(1);
  }

  const publishable = posts
    .filter((post) => options.drafts || !post.draft)
    .sort((a, b) => (a.published < b.published ? 1 : a.published > b.published ? -1 : a.slug.localeCompare(b.slug)));

  if (options.check) {
    console.log(`Checked ${sources.length} post(s). ${warningCount} warning(s). No errors.`);
    return;
  }

  const blogDir = path.join(options.outDir, 'blog');
  fs.mkdirSync(blogDir, { recursive: true });

  const expected = new Set(publishable.map((post) => `${post.slug}.html`));
  const written = [];

  for (const post of publishable) {
    const file = path.join(blogDir, `${post.slug}.html`);
    if (writeIfChanged(file, renderPost(post))) written.push(post.route);
  }

  // Remove pages whose source is gone or has become a draft, so the public
  // directory never drifts from content/blog.
  const orphans = fs
    .readdirSync(blogDir)
    .filter((name) => name.endsWith('.html') && !expected.has(name));
  for (const orphan of orphans) {
    fs.unlinkSync(path.join(blogDir, orphan));
    console.log(`removed  /blog/${orphan.replace(/\.html$/, '')}`);
  }

  const indexChanged = writeIfChanged(path.join(options.outDir, 'blog.html'), renderIndex(publishable));
  const sitemapChanged = updateSitemap(options.outDir, publishable.filter((post) => !post.draft));

  console.log('');
  console.log(`Posts built: ${publishable.length}${options.drafts ? ' (drafts included)' : ''}`);
  publishable.forEach((post) => {
    console.log(`- ${post.route}  ${post.wordCount} words  ${post.draft ? '[draft] ' : ''}${post.published}`);
  });
  console.log('');
  console.log(`Pages changed: ${written.length}${indexChanged ? ' + /blog' : ''}${sitemapChanged ? ' + sitemap.xml' : ''}`);
  console.log(`Warnings: ${warningCount}`);
  console.log('');
  if (options.drafts && publishable.some((post) => post.draft)) {
    console.log(`WARNING: drafts were written to ${path.relative(repoRoot, options.outDir) || options.outDir}.`);
    console.log('They are noindex and out of the sitemap, but do not commit this output.');
    console.log('Run "npm run blog:build" to strip them first.');
    console.log('');
  }
  console.log('How to run: npm run blog:build');
}

main();
